export default {
  login: "AlbanRenahy",
  id: 55736796,
  node_id: "MDQ6VXNlcjU1NzM2Nzk2",
  avatar_url: "https://avatars.githubusercontent.com/u/55736796?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AlbanRenahy",
  html_url: "https://github.com/AlbanRenahy",
  followers_url: "https://api.github.com/users/AlbanRenahy/followers",
  following_url:
    "https://api.github.com/users/AlbanRenahy/following{/other_user}",
  gists_url: "https://api.github.com/users/AlbanRenahy/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/AlbanRenahy/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AlbanRenahy/subscriptions",
  organizations_url: "https://api.github.com/users/AlbanRenahy/orgs",
  repos_url: "https://api.github.com/users/AlbanRenahy/repos",
  events_url: "https://api.github.com/users/AlbanRenahy/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/AlbanRenahy/received_events",
  type: "User",
  site_admin: false,
  name: "Alban Renahy",
  company: "école O'Clock",
  blog: "albanrenahy.com",
  location: "région de Lille",
  email: null,
  hireable: null,
  bio: "Je recherche actuellement un stage ou premier emploi en tant que developpeur web. Disponible pour me déplacer sur toute la France et à l'étranger.",
  twitter_username: null,
  public_repos: 33,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2019-09-24T08:15:27Z",
  updated_at: "2021-05-12T11:52:04Z",
};
